.add_ssh:
  before_script:
    - which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)
    - apt-get update -y && apt-get install git zip unzip -y
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - (umask  077; echo $SSH_PRIVATE_KEY | base64 -d > ~/.ssh/id_rsa)
    - ssh-keyscan -t rsa -H $HOST >> ~/.ssh/known_hosts
    - ssh-keyscan -t rsa -H $DEV_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts